name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Hostinger
      env:
        HOSTINGER_HOST: cmkdigitalinnovation.com
        HOSTINGER_USER: u755328260
        HOSTINGER_KEY: |
          b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDrIrWV3s
          Lti980dacgaivoAAAAGAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQC8iEspfJpx
          /bDGlrRbAHj46VXRj/W9fGI8+zvPsna0MsovJ/ML312DXmn9eIFjzZ+mjYos75apcv/PR1
          bnwr7oB2KNnlyBBWQF+jidF+MWXwciV1F4a0DQ+ndQSoHvgKw1iswfpJkxoyPr1j7IJDZu
          5BTyhggxoWfKHwQjgX+jVQH7yK7MfVyxs0YMTv4/abayOjoUSWkLLS+G++gBpwg2tEWBmW
          uuUapRljuL8zu8GO53Z/gM3mHbxrfZaV5YKI25/w3KrmHsM1CErsnef7r/Wrf1H51UVBdW
          eHopi0kaSjpah4leoODeM9L/Ge+bgyY+WLmANoStISGXxPjT1PchP/3dQLfrfP8V4O2JOP
          F81dc/qoJafXn29KqIVtkvM2W0HGxFFjaMS3t8NyiRZoe9qk9vcipn0rD9WZ+LmBBnIHmI
          I97Z6iQ/VIIbfz5FUOUKxJp9Cqnj/eTOD2s8+93wnsBijQO64/6NsVwIv7PbQHAgw5xYPv
          JEvH5Brp41IS1yRjlzOoe19xwPx2BaDVsNVn/MeYSRWg9g/SlBmBAFc0MP4fKUdwKbvi38
          iMeHGz41O6ba5r5cj/c5JvfH77ikP3dx8HY2hhhFNxjojg3b6RFNb9j2g7MTMd6dXGl6IX
          U1ppIw2Ftw2hMZFugL5aAtHlnwgCDWTzz9bdBcr7k3ZQAAB1D1TuRT8eIbBj22MxPL8KBe
          GFnudeWd3Cv+WGnnKaTPLHRzu22wfesaDyo5e133OASMlsJcaBjKHZrCPkEFDqIAX6yXkh
          eonLjBB23235QbCpIK9Yda6R8WUOqUjQK+0XdgeMA1/5riqHMGKO1uTJchHoooi5AITOaz
          SD7YlDSAYa9c5pTmtXcQPi8B5l7kE5hNTLHMCePvKwGYL7d4MEHs0V4/TlsbW9TqvuPhym
          jkKw0AroJHUdiBeEgrh2QvlCjBiTvnAo2LeruClwqlp+tGEwHq/iCH+Sf5d1PbcJai7pFx
          AiMi9uS/0sgwf6b44wEpjiumsfzXOeqr4vplj9W1OQu6Veu0/f63Mz0CGgQeqQnM2vhpns
          zR3+6QyKFM4VKa9YHrURhALVsQYudxopCkGmjmqDMea0R33C0aSwalqOaqjUjONJknEXHF
          e/e5xdVdS9icI15r+KMmFHpH8PpJ3LXsY76Oeoz5VE+V0lQM+7Ok4vGdbEC40XHOd6jiSv
          7XFLmNpJv+BzPunXWBkW+vdy8kHyEZ//dK1dta2fwaSLmeooRO3H8OuSfCuDuu67Y46zEx
          EJ7cy9f7pYX4VOLeRXpeNHcdcI+WZCHwb/fLhgb9dzMjjqbnBKMaSXbiYggGqdFtNZqdWr
          CPk6p4xINb/KBL02yy3GJI6nmxeNBPB1Zjq738gLwNOVfMgNCxrrMx8EM0Wz6N9aKDUU5Q
          twSUI9uSQe9MtSOTktOcn/YB6/9ZCX43VTEiYBmwD4QrhXZ0cMh8tQR/htX/NZsKPjGzPh
          aBZ2U4mrfnUEofk3DASdhNIml+YkBVCcvAKpTtIcBj7jFfk5rZr08j0mQTRsZQ6f+ackpz
          FocFs0MHrQ33v4e3/PMAKtTM2BVRrp9FV4M+9yacrsZuLj/3swJh1kOisMncq+211Mf4gB
          AerO/93oLXdMETnSt9xbsXgX9ZXlOzSxHQstON62cmXn6lrb1PeyCUGGagDqQ/Ax4DhcAj
          nA3jNqB/Fbb6lEXC4ELJVcTG7J4tNnSEzSd7VDAEzTDDK/TXctQuzL0VYfn3GhaIxi2fte
          CBUgxfafc0R8lQgAzDt+YlKppa2EkOnO4Gw6UjpRFgx2/cwKP5sfctNluGPnaqvBX1kg4j
          UhyPaVG0hiBfIhnOMGzyF8wcZI8ytFoocKe1AJnRnVdKM3QrhnJLSAG5z2hXF78FvW3OwF
          DJNIjUkOWRu/Wh0x/AL3SWNMwQBxVnRdXBknH9IYKftInGOUB/vqRRCQRH6owY3zz7whj3
          ALzQ+gW5ZXaQl6qWXnVMpxM7jJd5URzX5pnSAiJK3Wa8r8pTK0ajR4bwdjjde44c7pE4UD
          8sw5ExKunGo2a4gxvd4ERXT5YJwFh5c0QBTOkScfwfZ1Ee1Rp9w3EhFBN94pyQYHP5VzMt
          xCvit/Jnz9tBFhSidNv5W7h1HtB4r8kfa/Plojy6/08KskAUhRIJEgqaSfv2rVLZF30HWX
          9UgkwbMf2uSlnUKoVMvlKUdhYIb11oqbYCHq5qQgfd2sFFFWqP0XPdu1sTIlJdi4+MTVlR
          zbxSjSphwLHXLsJ9FWZsAY+HcPmckUlwEAgrmrDugJeGRv/RlrdpBQiQE4TylHGUwsKjrU
          XQJ9B1D0nzHxY2Slnrsn0x/f+cG0ihGjL/NQojZTn+SciSox4IuP+u2WCWSg9ll436HxJ/
          ZU1Pm8ffaQQiukG0ICmYeomP/mmFxAtSmzlgBK8QIwWVAr81R+65QnYZ2OoH0dykKn2mv9
          3kmxfcSPNAes+vEovLUoFe2I38RnmZC+iBGr9xjAqg9QkHtFR7mgn6ihpIjW5yGvkK0KbW
          ayE/Aebxp78ib9GXuIs4mq9LkzgZfVXQLRhB7w5+c/OJ+kkNolJBjq3fPf1s3IdKwKrglr
          Njbc48mxXZxeC4HEPughHXCXsijuYAwoJpmdN/qZF9IAv9h2fUjdKC/G+SaAylzuKIVu36
          XFcJksZoAly4HG/Uonb3//ZE4vRIesMlWGfSBhAtV9rcC7BgwHdKDHlyBaSum/6dqAzwY9
          0OzWbKlMaihGD1jlbCP/HYLA9JKs4ylKPZ39WLWj/3RnuKv7KK7lmGBXrfwhoWDPj/DQ53
          nB4Irg86lw8CZun6Zh7YA4w+CRS469Y5+5SlfsTI5Ca6VWD933ERNvbe4koNOVeinnn9ML
          EPLx6ExK4lAsg/UVk0xFFhmo3CpyOVAiysnH6UzxvknhZP75wYQHFMrES9PAozAff5U1bZ
          C2fddt11Y9Bo5Edx+4dOPhny14XUycj9CkkXAw4D6lFtSo9xXoculsif9tnzNEGQtJha6E
          YHIw1MTtMezE5NUukJ7lKJh+UB4hj9rP7FlPdq7JQmHMgIaWWZwiK2nCqBu61nx98zWxYS
          +0TR0GTQY0f+P3SQto01tjpy+R2Wgib8mpRnpbz8J1zF6uTPIEAK+waamVz9VgT0hLX8/r
          au6DhAad/ZI6oOFVI+XWZsjE0=
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOSTINGER_KEY $HOSTINGER_USER@$HOSTINGER_HOST '
        cd /domains/cmkdigitalinnovation.com/public_html/stockytest &&
        git pull origin main &&
        composer install --no-dev --prefer-dist --optimize-autoloader &&
        php artisan migrate --force'
